In [19]:
from array import array
import numpy
arrayOnes = numpy.array([[numpy.ones(3)],[numpy.ones(3)],[numpy.ones(3)]])
arrayOnes

array([[[ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.]]])

In [20]:
from array import array
import numpy
array72 = [numpy.zeros(2),numpy.zeros(2),numpy.zeros(2),numpy.zeros(2),numpy.zeros(2),numpy.zeros(2),numpy.zeros(2)]
array72

[array([ 0.,  0.]),
 array([ 0.,  0.]),
 array([ 0.,  0.]),
 array([ 0.,  0.]),
 array([ 0.,  0.]),
 array([ 0.,  0.]),
 array([ 0.,  0.])]

In [25]:
array25 = numpy.arange(0,25,1,dtype=int)
array25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
array100 = numpy.linspace(0,100,25)
array100

array([   0.        ,    4.16666667,    8.33333333,   12.5       ,
         16.66666667,   20.83333333,   25.        ,   29.16666667,
         33.33333333,   37.5       ,   41.66666667,   45.83333333,
         50.        ,   54.16666667,   58.33333333,   62.5       ,
         66.66666667,   70.83333333,   75.        ,   79.16666667,
         83.33333333,   87.5       ,   91.66666667,   95.83333333,  100.        ])

In [28]:
arrayMesh = numpy.mgrid[0:5,0:5]
arrayMesh

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [31]:
array5 = [numpy.zeros(5),numpy.zeros(5),numpy.zeros(5),numpy.zeros(5),numpy.zeros(5)]
array5[0,0] = 1
array5[1,1] = 2
array5


SyntaxError: can't assign to function call (<ipython-input-31-73758811b629>, line 2)